### ISSUE TITLE
support SPM mode for FIM prompts

### ISSUE THREAD

**Issue by erfanium** [bigcode-project/starcoder2#14]
from fim paper (https://arxiv.org/pdf/2207.14255.pdf) section 3.1: SPM mode can be used to reuse kv cache across completion requests.

SPM modes can enable further latency optimization (which is very important in case of code completion tools). is there any reason that startcoder models are using normal PSM mode?

**Comment by loubnabnl** [comment]
We train with both modes (50% PSM and 50% SPM), similarily to StarCoder (cf [paper](https://arxiv.org/pdf/2402.19173.pdf)). So you can also try SPM mode for inference.
<img width="654" alt="image" src="https://github.com/bigcode-project/starcoder2/assets/44069155/28ee2d6f-1495-40c8-81d6-2c5b2014ce83">

**Comment by erfanium** [comment]
Got it. thanks!
