### ISSUE TITLE
Megatron model weights for StarCoder2-15B 

### ISSUE THREAD

**Issue by christiancosgrove** [bigcode-project/starcoder2#15]
A year ago, the raw Megatron weights for StarCoder [were released](https://github.com/bigcode-project/starcoder/issues/25).

Would it be possible to release the Megatron weights for StarCoder2, especially the 15B variant?

Also, publishing a script to convert StarCoder2 from Megatron format to HuggingFace format would be helpful. Thanks!

**Comment by loubnabnl** [comment]
The 15B model was trained with Megatron-Nemo you can find instructions for using the checkpoint here https://docs.nvidia.com/nemo-framework/user-guide/latest/llms/starcoder2/

**Comment by christiancosgrove** [comment]
Thank you!
